config/routes.rb
WincorNixdorf::Application.routes.draw do


  resources :pickups do
  
  resources :deliveries do
  resources :delivery_units
  end
  end


  resources :admins

  get 'admin/:admin_id/products' => 'products#index'

  get 'get_token/:name/:password' => 'admins#get_token'
  get 'WebModSignOn/:name/:password' => 'admins#get_token'
  
  get "webmodesessions/new"
  
  get 'get_product/:id' => 'products#get_product'
  get 'WebModBarcodeTemplate/:id' => 'products#get_product'
  
  resources :web_mode_sign_ons
  
  get 'payment_history/:admin_id' => 'products#get_all_products', :as => :payment_path
  get 'WebModTotal' => 'products#WebModTotal'
  
  get 'WebModPayment/:user_id' => 'products#WebModPayment'
  
  get 'api' => 'pickups#api'
  get "api/v1/pickup/:code/get_deliveries" => "pickups#get_deliveries"

  devise_for :users

  resources :products

  root :to => "pickups#index"
  
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<h1>Listing Users</h1>
<table class="bordered-table zebra-striped">

  <thead>
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th colspn="3"></th>
  </tr>
  </thead>
  <tbody>
<% @admins.each do |admin| %>
  <tr>
    <td><%= admin.name %></td>
    <td><%= admin.password %></td>
    <td><%= link_to 'Show', admin %></td>
    <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
    <td><%= link_to 'Destroy', admin, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
  </tbody>
</table>

<br />

<%= link_to 'New user', new_admin_path, :class => "btn info" %>

app/views/admins/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<table class="bordered-table">
 <tr>
  <td><b>Name:</b></td>
  <td><%= @admin.name %></td>
 </tr>

 <tr>
  <td><b>Password:</b></td>
  <td><%= @admin.password %></td>
 </tr>
</table> 


<%= link_to 'Edit', edit_admin_path(@admin), :class => "btn info" %> 
<%= link_to 'Back', admins_path, :class => "btn"%>