config/routes.rb
WincorNixdorf::Application.routes.draw do


  resources :pickups do
  
  resources :deliveries do
  resources :delivery_units
  end
  end


  resources :admins

  get 'admin/:admin_id/products' => 'products#index'

  get 'get_token/:name/:password' => 'admins#get_token'
  get 'WebModSignOn/:name/:password' => 'admins#get_token'
  
  get "webmodesessions/new"
  
  get 'get_product/:id' => 'products#get_product'
  get 'WebModBarcodeTemplate/:id' => 'products#get_product'
  
  resources :web_mode_sign_ons
  
  get 'payment_history/:admin_id' => 'products#get_all_products', :as => :payment_path
  get 'WebModTotal' => 'products#WebModTotal'
  
  get 'WebModPayment/:user_id' => 'products#WebModPayment'
  
  get 'api' => 'pickups#api'
  get "api/v1/pickup/:code/get_deliveries" => "pickups#get_deliveries"

  devise_for :users

  resources :products

  root :to => "pickups#index"
  
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/pickup.rb
class Pickup < ActiveRecord::Base

has_many :deliveries
end

app/controllers/pickups_controller.rb
class PickupsController < ApplicationController
  # GET /pickups
  # GET /pickups.xml
  def index
    @pickups = Pickup.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pickups }
    end
  end

  # GET /pickups/1
  # GET /pickups/1.xml
  def show
    @pickup = Pickup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pickup }
    end
  end

  # GET /pickups/new
  # GET /pickups/new.xml
  def new
    @pickup = Pickup.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pickup }
    end
  end

  # GET /pickups/1/edit
  def edit
    @pickup = Pickup.find(params[:id])
  end

  # POST /pickups
  # POST /pickups.xml
  def create
    @pickup = Pickup.new(params[:pickup])

    respond_to do |format|
      if @pickup.save
        format.html { redirect_to(@pickup, :notice => 'Pickup was successfully created.') }
        format.xml  { render :xml => @pickup, :status => :created, :location => @pickup }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pickup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pickups/1
  # PUT /pickups/1.xml
  def update
    @pickup = Pickup.find(params[:id])

    respond_to do |format|
      if @pickup.update_attributes(params[:pickup])
        format.html { redirect_to(@pickup, :notice => 'Pickup was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pickup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pickups/1
  # DELETE /pickups/1.xml
  def destroy
    @pickup = Pickup.find(params[:id])
    @pickup.destroy

    respond_to do |format|
      format.html { redirect_to(pickups_url) }
      format.xml  { head :ok }
    end
  end
 
  def api
  end
  
  
  def get_deliveries
#	@pickup = Pickup.find_by_code(params[:code]).include(:deliveries)
@pickups = Pickup.find_all_by_code(params[:code], :include =>{:deliveries => :delivery_units})
	p = @pickups.collect do |pi|
		{ 
			:name => pi.name, 
			:deliveries => pick_up_deliveries(pi.deliveries)
		}
	end
	render :json => p
  end
 
 private 
  def pick_up_deliveries(d)
  		d.map do |de|
		{:transfer_no => de.transfer_no,
    	:ordered_by => de.ordered_by,
      :delivery_note => de.delivery_note,
      :po_no => de.po_no,
      :deliver_date => de.deliver_date,
      :phone_no => de.phone_no,
      :address => de.address,
      :delivery_units => de.delivery_units }
  		end
  end
  
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/views/pickups/_form.html.erb
<%= form_for(@pickup) do |f| %>
  <% if @pickup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pickup.errors.count, "error") %> prohibited this pickup from being saved:</h2>

      <ul>
      <% @pickup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn" %>
  </div>
<% end %>

app/views/pickups/api.html.erb
<h4>Webservices API</h4>
<table class="bordered-table zebra-striped">
<tr>
<td><a target="new" href="/WebModSignOn/1111/1111.json">WebModSignOn(1111, 1111)</a></td>
</tr>
<tr><td><a target="new" href="/api/v1/pickup/123/get_deliveries">Get all the deliveries and its units <b>api/v1/pickup/pickup_id/get_deliveries</b></a></td></tr>
</table>

app/views/pickups/edit.html.erb
<% content_for :title_head, "Editing pickup"%>
<%= render 'form' %>

<%= link_to 'Show', @pickup, :class => "btn" %> 
<%= link_to 'Back', pickups_path,:class => "btn" %>

app/views/pickups/index.html.erb
<% content_for :title_head,  "Listing pickups"%>
<table class="bordered-table zebra-striped">
 <thead>
  <tr>
    <th>Name</th>
    <th>Code</th>
    <th colspn="4"></th>
  </tr>
 </thead>
 <tbody>
<% @pickups.each do |pickup| %>
  <tr>
    <td><%= pickup.name %></td>
    <td><%= pickup.code %></td>
    <td><%= link_to "Deliveries", pickup_deliveries_path(pickup)%></td>
    <td><%= link_to 'Show', pickup %></td>
    <td><%= link_to 'Edit', edit_pickup_path(pickup) %></td>
    <td><%= link_to 'Destroy', pickup, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
 </tbody>
</table>

<br />

<%= link_to 'New Pickup', new_pickup_path, :class => "btn info" %>

app/views/pickups/new.html.erb
<% content_for :title_head, "New pickup"%>
<%= render 'form' %>

<%= link_to 'Back', pickups_path, :class => "btn" %>

app/views/pickups/show.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title_head, @pickup.name %>
<table class="bordered-table">
  <tbody>
    <tr>
      <td><b>Name:</b></td>
      <td> <%= @pickup.name %></td>
    </tr>
    <tr>
      <td><b>Code:</b></td>
      <td><%= @pickup.code %></td>
    </tr>
    </tbody>
</table>

<%= link_to 'Edit', edit_pickup_path(@pickup), :class=> "btn" %> 
<%= link_to 'Back', pickups_path, :class=> "btn" %>