config/routes.rb
WincorNixdorf::Application.routes.draw do


  resources :pickups do
  
  resources :deliveries do
  resources :delivery_units
  end
  end


  resources :admins

  get 'admin/:admin_id/products' => 'products#index'

  get 'get_token/:name/:password' => 'admins#get_token'
  get 'WebModSignOn/:name/:password' => 'admins#get_token'
  
  get "webmodesessions/new"
  
  get 'get_product/:id' => 'products#get_product'
  get 'WebModBarcodeTemplate/:id' => 'products#get_product'
  
  resources :web_mode_sign_ons
  
  get 'payment_history/:admin_id' => 'products#get_all_products', :as => :payment_path
  get 'WebModTotal' => 'products#WebModTotal'
  
  get 'WebModPayment/:user_id' => 'products#WebModPayment'
  
  get 'api' => 'pickups#api'
  get "api/v1/pickup/:code/get_deliveries" => "pickups#get_deliveries"

  devise_for :users

  resources :products

  root :to => "pickups#index"
  
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  belongs_to :pickup
  has_many :delivery_units
end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
  before_filter :get_pickup
  
  def get_pickup
  @pickup = Pickup.find(params[:pickup_id])
  end
  
  def index
    @deliveries = @pickup.deliveries
  end

  def show
    @delivery = Delivery.find(params[:id])
  end

  def new
    @delivery = Delivery.new
  end

  def edit
    @delivery = Delivery.find(params[:id])
  end

  def create
    @delivery = @pickup.deliveries.new(params[:delivery])

      if @delivery.save
 redirect_to(pickup_deliveries_path(@pickup), :notice => 'Delivery was successfully created.') 
      else
render :action => "new" 
    end
  end

  def update
    @delivery = Delivery.find(params[:id])
      if @delivery.update_attributes(params[:delivery])
redirect_to(pickup_deliveries_path(@pickup), :notice => 'Delivery was successfully updated.') 
      else
render :action => "edit" 
    end
  end

def destroy
    @delivery = Delivery.find(params[:id])
    @delivery.destroy
	 redirect_to(pickup_deliveries_path(@pickup))
  end  
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/views/deliveries/_form.html.erb
<%= form_for([@pickup, @delivery]) do |f| %>
  <% if @delivery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@delivery.errors.count, "error") %> prohibited this delivery from being saved:</h2>

      <ul>
      <% @delivery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :transfer_no %><br />
    <%= f.text_field :transfer_no %>
  </div>
  <div class="field">
    <%= f.label :ordered_by %><br />
    <%= f.text_field :ordered_by %>
  </div>
  <div class="field">
    <%= f.label :delivery_note %><br />
    <%= f.text_area :delivery_note, :size => "20x8" %>
  </div>
  <div class="field">
    <%= f.label :po_no %><br />
    <%= f.text_field :po_no %>
  </div>
  <div class="field">
    <%= f.label :deliver_date %><br />
    <%= f.date_select :deliver_date %>
  </div>
  <div class="field">
    <%= f.label :pickup %><br />
    <%= f.text_field :pickup_id %>
  </div>
  <div class="field">
    <%= f.label :phone_no %><br />
    <%= f.text_field :phone_no %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address, :size => "20x8" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn" %>
  </div>
<% end %>

app/views/deliveries/edit.html.erb
<% content_for :title_head,  "Editing delivery"%>
<%= render 'form' %>

<%= link_to 'Show', pickup_delivery_path(@pickup, @delivery) , :class => "btn"%> 
<%= link_to 'Back', pickup_deliveries_path(@pickup) , :class => "btn"%>

app/views/deliveries/index.html.erb
<% content_for :title_head,  "Listing deliveries"%>
<table class="bordered-table zebra-striped" width="680px;">
 <thead>
  <tr>
    <th>Transfer no</th>
    <th>Ordered by</th>
    <th>Delivery note</th>
    <th>Po no</th>
    <th>Deliver date</th>
    <th>Phone no</th>
    <th colspn="4"></th>
   
  </tr>
 </thead>
 <tbody>
<% @deliveries.each do |delivery| %>
  <tr>
    <td><%= delivery.transfer_no %></td>
    <td><%= delivery.ordered_by %></td>
    <td><%= delivery.delivery_note %></td>
    <td><%= delivery.po_no %></td>
    <td><%= delivery.deliver_date %></td>
    <td><%= delivery.phone_no %></td>
     <td><%= link_to "Units", pickup_delivery_delivery_units_path(@pickup, delivery) %></td>
    <td><%= link_to 'Show', pickup_delivery_path(@pickup, delivery) %></td>
    <td><%= link_to 'Edit', edit_pickup_delivery_path(@pickup, delivery) %></td>
    <td><%= link_to 'Destroy', pickup_delivery_path(@pickup, delivery), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Delivery', new_pickup_delivery_path(@pickup), :class => "btn info" %>

app/views/deliveries/new.html.erb
<% content_for :title_head,  "New delivery" %>
<%= render 'form' %>

<%= link_to 'Back', pickup_deliveries_path(@pickup) , :class => "btn"%>

app/views/deliveries/show.html.erb
<% content_for :title_head,  @delivery.ordered_by  %>
<p id="notice"><%= notice %></p>
<table class="bordered-table">
  <tbody>
    <tr>
      <td><b>Transfer no:</b></td>
      <td><%= @delivery.transfer_no %></td>
    </tr>
    <tr>
      <td><b>Ordered by:</b></td>
      <td><%= @delivery.ordered_by %></td>
    </tr>
    <tr>
      <td><b>Delivery note:</b></td>
      <td><%= @delivery.delivery_note %></td>
    </tr>
    <tr>
      <td><b>Po no:</b></td>
      <td><%= @delivery.po_no %></td>
    </tr>
    <tr>
      <td><b>Deliver date:</b></td>
      <td><%= @delivery.deliver_date %></td>
    </tr>
    <tr>
      <td><b>Phone no:</b></td>
      <td><%= @delivery.phone_no %></td>
    </tr>
    <tr>
      <td><b>Address:</b></td>
      <td><%= @delivery.address %></td>
    </tr>
  </tbody>
</table>


<%= link_to 'Edit', edit_pickup_delivery_path(@pickup, @delivery), :class => "btn" %> 
<%= link_to 'Back', pickup_deliveries_path(@pickup), :class => "btn" %>